// Replace the content in <>
// Briefly describe the software. Use consistent and clear branding. 
// Include the benefits of using the software on AWS, and provide details on usage scenarios.

//TODO Give an overview of the QS itself, as well as some additional detail on the Rigado kit too.
// Make sure to talk about Allegro kit before using it as a heading, so that customers know its from Rigado.

=== The Allegro Kit for AWS

This AWS QuickSitart has been created and pre-configured for the Rigado Allegro Kit for AWS. The kit aims at accelerating IoT proofs of concepts and pilot projects. It can be setup in a few minutes to demonstrate real-world scenarios with live data for a variety of commercial spaces: retail, travel &
hospitality, smart buildings, and more. It uses  production sensors and cloud components based on Rigado and AWS IoT reference architectures. It is composed of:

* The Rigado Plug & Play Sensor Network: Cascade gateways, temperature & humidity sensors, alert buttons, door sensors, asset trackers, and more.
* QuickStart Onboarding: A pre-integrated setup wizard creates a live demo application in minutes.
* Preconfigured dashboard in AWS IoT SiteWise and Amazon QuickSight providing a no-code approach to quickly building a pilot IoT project on AWS.



